title: Goal Moderator
description: The light version of Goal mentor is now available in the ChatGBT Store

show_downloads: false
github:
  zip_url: http://example.com/download.zip


google_analytics:
theme: jekyll-theme-cayman